version: '3.1'
services:
  db:
    image: postgres:13-alpine
    container_name: jade_mermaid_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
